export interface PredefinedRitual {
  id: string
  name: string
  level: number
  type: string
  castingTime: string
  range: string
  target: string
  duration: string
  resistance?: string
  components?: string
  description: string
  damage?: string
  damageType?: string
}

export const predefinedRituals: PredefinedRitual[] = [
  {
    id: "amaldicoar-arma",
    name: "Amaldiçoar Arma",
    level: 1,
    type: "VARIA",
    castingTime: "padrão",
    range: "toque",
    target: "1 arma corpo a corpo ou pacote de munição",
    duration: "cena",
    description:
      "Quando aprender este ritual, escolha um elemento entre Conhecimento, Energia, Morte e Sangue. Este ritual passa a ser do elemento escolhido. Você imbui a arma ou munições com o elemento, fazendo com que causem +1d6 de dano do tipo do elemento.\n\nDiscente (+2 PE): muda o bônus de dano para +2d6. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o bônus de dano para +4d6. Requer 3º círculo e afinidade.",
    damage: "+1d6",
    damageType: "Variável",
  },
  {
    id: "arma-de-sangue",
    name: "Arma de Sangue",
    level: 1,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 arma corpo a corpo",
    duration: "sustentada",
    description:
      "A arma é recoberta por veias carmesim e passa a exalar uma aura de violência. Ela fornece +2 em testes de ataque e +1 na margem de ameaça.\n\nDiscente (+2 PE): muda o bônus para +5 em testes de ataque. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o bônus para +5 em testes de ataque e +2 na margem de ameaça e no multiplicador de crítico. Requer 3º círculo e afinidade.",
  },
  {
    id: "armadura-de-sangue",
    name: "Armadura de Sangue",
    level: 1,
    type: "SANGUE",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description:
      'Seu sangue escorre para fora do corpo, cobrindo-o sob a forma de uma carapaça que fornece +5 em Defesa. Esse bônus é cumulativo com outros rituais, mas não com bônus fornecido por equipamento.\n\nDiscente (+5 PE): muda o efeito para "fornece +10 na Defesa e resistência a balístico, corte, impacto e perfuração 5". Requer 3º círculo.\n\nVerdadeiro (+9 PE): muda o efeito para "fornece +15 na Defesa e resistência a balístico, corte, impacto e perfuração 10". Requer 4º círculo e afinidade.',
  },
  {
    id: "cicatrizacao",
    name: "Cicatrização",
    level: 1,
    type: "MORTE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    description:
      'Você acelera o tempo ao redor das feridas do alvo, que cicatrizam instantaneamente. O alvo recupera 3d8+3 PV, mas envelhece 1 ano automaticamente.\n\nDiscente (+2 PE): aumenta a cura para 5d8+5 PV. Requer 2º círculo.\n\nVerdadeiro (+9 PE): muda o alcance para "curto", o alvo para "seres escolhidos" e aumenta a cura para 7d8+7 PV. Requer 4º círculo e afinidade com Morte.',
    damage: "3d8+3",
    damageType: "Cura",
  },
  {
    id: "cineraria",
    name: "Cinerária",
    level: 1,
    type: "MEDO",
    castingTime: "padrão",
    range: "curto",
    target: "nuvem de 6m de raio",
    duration: "cena",
    description:
      "Você manifesta uma névoa carregada de essência paranormal. Rituais conjurados dentro da névoa têm sua DT aumentada em +5.\n\nDiscente (+2 PE): além do normal, rituais conjurados dentro da névoa custam –2 PE.\n\nVerdadeiro (+5 PE): além do normal, rituais conjurados dentro da névoa causam dano maximizado.",
  },
  {
    id: "coincidencia-forcada",
    name: "Coincidência Forçada",
    level: 1,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    description:
      "Você manipula os caminhos do caos para que o alvo tenha mais sorte. O alvo recebe +2 em testes de perícias.\n\nDiscente (+2 PE): muda o alvo para aliados à sua escolha. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o alvo para aliados à sua escolha e o bônus para +5. Requer 3º círculo e afinidade.",
  },
  {
    id: "compreensao-paranormal",
    name: "Compreensão Paranormal",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser ou objeto",
    duration: "cena",
    resistance: "Vontade anula",
    description:
      'O ritual confere a você compreensão sobrenatural da linguagem. Se tocar um objeto contendo informação (ou livro, um dispositivo com uma gravação...), você entende as palavras mesmo que não conheça seu idioma, contanto que se trate de um idioma humano (não funciona com símbolos ou sigilos paranormais). Se tocar uma pessoa, pode se comunicar com ela como se falassem um idioma em comum. Se tocar um ser não inteligente, como um animal, pode perceber seus sentimentos básicos, como medo ou felicidade. Um alvo involuntário tem direito a um teste de Vontade.\n\nDiscente (+2 PE): muda o alcance para "curto" e o alvo para "alvos escolhidos". Você pode entender todos os alvos afetados. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o alcance para "pessoal" e o alvo para "você". Em vez do normal, você pode falar, entender e escrever qualquer idioma humano. Requer 3º círculo.',
  },
  {
    id: "consumir-manancial",
    name: "Consumir Manancial",
    level: 1,
    type: "MORTE",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description:
      'Você suga uma pequena porção do tempo de vida de plantas, insetos e até mesmo do solo ao redor, gerando lodo e recebendo 3d6 pontos de vida temporários. Os PV temporários desaparecem ao final da cena.\n\nDiscente (+2 PE): muda os PV temporários recebidos para 6d6. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o alvo para "área: esfera com 6m de raio centrada em você" e a resistência para "Fortitude reduz à metade". Em vez do normal, você suga energia de todos os seres vivos na área, causando 3d6 pontos de dano de Morte em cada um e recebendo PV temporários iguais ao dano total causado até o final da cena. Requer 3º círculo e afinidade.',
    damage: "3d6",
    damageType: "Temporário",
  },
  {
    id: "corpo-adaptado",
    name: "Corpo Adaptado",
    level: 1,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 pessoa ou animal",
    duration: "cena",
    resistance: "Vontade parcial, Fortitude parcial",
    description:
      'Este ritual modifica a biologia do alvo para permitir a sobrevivência em ambientes hostis. O alvo fica imune a calor e frio extremos, pode respirar na água se respirar ar (ou vice-versa) e não sufoca em fumaça densa.\n\nDiscente (+2 PE): muda a duração para 1 dia.\n\nVerdadeiro (+5 PE): muda o alcance para "curto" e o alvo para "pessoas ou animais escolhidos".',
  },
  {
    id: "decadencia",
    name: "Decadência",
    level: 1,
    type: "MORTE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Fortitude reduz à metade",
    description:
      'Espirais de trevas envolvem sua mão e definham o alvo, que sofre 2d8+2 pontos de dano de Morte.\n\nDiscente (+2 PE): muda a resistência para "nenhuma" e o dano para 3d8+3. Como parte da execução do ritual, você transfere as espirais para uma arma e faz um ataque corpo a corpo contra o alvo com esta arma. Se acertar, causa o dano da arma e do ritual, somados.\n\nVerdadeiro (+5 PE): muda o alcance para "pessoal" o alvo para "área: explosão com 6m de raio" e o dano para 8d8+8. As espirais afetam todos os seres na área. Requer 3º círculo.',
    damage: "2d8+2",
    damageType: "Morte",
  },
  {
    id: "definhar",
    name: "Definhar",
    level: 1,
    type: "MORTE",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    resistance: "Fortitude parcial",
    description:
      'Você dispara uma lufada de cinzas que drena as forças do alvo. A alvo fica fatigado. Se passar no teste de resistência, em vez disso fica vulnerável.\n\nDiscente (+2 PE): em vez do normal, o alvo fica exausto. Se passar na resistência, fica fatigado. Requer 2º círculo.\n\nVerdadeiro (+5 PE): como discente, mas muda o alvo para "até 5 seres". Requer 3º círculo e afinidade com Morte.',
  },
  {
    id: "distorcer-aparencia",
    name: "Distorcer Aparência",
    level: 1,
    type: "SANGUE",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    resistance: "Vontade desacredita",
    description:
      "Você modifica sua aparência física para se transformar em outra pessoa. Isso inclui altura, peso, tom de pele, cor de cabelo, timbre de voz, impressão digital, córnea etc. Você recebe +10 em testes de Enganação para disfarce, mas não recebe habilidades da nova forma nem modifica suas demais estatísticas.",
  },
  {
    id: "eletrocussao",
    name: "Eletrocussão",
    level: 1,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser ou objeto",
    duration: "instantânea",
    resistance: "Fortitude parcial",
    description:
      'Você manifesta e dispara uma corrente elétrica contra o alvo, que sofre 3d6 pontos de dano de eletricidade e fica vulnerável por uma rodada. Se passar no teste de resistência, sofre apenas metade do dano e evita a condição. Se usado contra objetos eletrônicos, este ritual causa o dobro de dano e ignora resistência.\n\nDiscente (+2 PE): muda o alvo para "área: linha de 30m". Você dispara um poderoso raio que causa 6d6 pontos de dano de Energia em todos os seres e objetos livres na área. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda a área para "alvos escolhidos". Em vez do normal, você dispara vários relâmpagos, um para cada alvo escolhido, causando 8d6 pontos de dano de Energia em cada. Requer 3º círculo.',
    damage: "3d6",
    damageType: "Eletricidade",
  },
  {
    id: "embaralhar",
    name: "Embaralhar",
    level: 1,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description:
      "Você cria três cópias ilusórias que se parecem com hologramas extremamente realistas. As cópias ficam ao seu redor e imitam suas ações, tornando difícil para um inimigo saber quem é o verdadeiro. Você recebe +6 na Defesa. Cada vez que um ataque contra você erra, uma das imagens desaparece e o bônus na Defesa diminui em 2. Um oponente deve ver as cópias para ser confundido. Se você estiver invisível, ou o atacante fechar os olhos, você não recebe o bônus (mas o atacante sofre as penalidades normais por não enxergar).\n\nDiscente (+2 PE): muda o número de cópias para 5 (e o bônus na Defesa para +10). Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda o número de cópias para 8 (e o bônus na Defesa para +16). Além do normal, toda vez que uma cópia é destruída, emite um clarão de luz. O ser que destruiu a cópia fica ofuscada por uma rodada. Requer 3º círculo.",
  },
  {
    id: "enfeiticar",
    name: "Enfeitiçar",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Vontade anula",
    description:
      "Este ritual torna o alvo prestativo. Ele não fica sob seu controle, mas percebe suas palavras e ações da maneira mais favorável possível. Você recebe um bônus de +10 em testes de Diplomacia com ele. Um alvo hostil ou que esteja envolvido em combate recebe +5 em seu teste de resistência. Se você ou seus aliados tomarem qualquer ação hostil contra o alvo, o efeito é dissipado e o alvo retorna à atitude que tinha antes (ou piorada, de acordo com o mestre)\n\nDiscente (+2 PE): em vez do normal, você sugere uma ação para o alvo e ele obedece. A sugestão deve ser feita de modo que pareça aceitável, a critério do mestre. Pedir que o alvo atire em seu companheiro, por exemplo, dissipa o efeito. Já sugerir a um guarda que descanse um pouco, de modo que você e seus aliados passem por ele, é aceitável. Quando o alvo executa a ação, o efeito termina. Você pode determinar uma condição específica para a sugestão: por exemplo, que o policial prenda a próxima pessoa de casaco verde que ele encontrar. Requer 2º círculo.\n\nVerdadeiro (+5 PE): afeta todos os alvos dentro do alcance. Requer 3º círculo.",
  },
  {
    id: "espirais-da-perdicao",
    name: "Espirais da Perdição",
    level: 1,
    type: "MORTE",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "cena",
    description:
      'Espirais surgem no corpo do alvo, tornando seus movimentos lentos. O alvo sofre –1d20 em testes de ataque.\n\nDiscente (+2 PE): muda a penalidade para –2d20. Requer 2º círculo.\n\nVerdadeiro (+8 PE): muda a penalidade para -2d20. e o alvo para "seres escolhidos". Requer 3º círculo.',
  },
  {
    id: "odio-incontrolavel",
    name: "Ódio Incontrolável",
    level: 1,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "cena",
    description:
      "O alvo entra em um frenesi, aumentando sua agressividade e capacidade de luta. Ele recebe +2 em testes de ataque e rolagens de dano corpo a corpo e resistência a balístico, corte, impacto e perfuração 5. Enquanto o efeito durar, o alvo não pode fazer nenhuma ação que exige calma e concentração (como usar a perícia Furtividade ou conjurar rituais), e deve sempre atacar um alvo em sua rodada, mesmo que seja um aliado se ele for o único a seu alcance.\n\nDiscente (+2 PE): além do normal, sempre que o alvo usar a ação agredir, pode fazer um ataque corpo a corpo adicional contra o mesmo alvo.\n\nVerdadeiro (+5 PE): muda o bônus de ataque e dano para +5 e o alvo passa a sofrer apenas metade do dano dos tipos balístico, corte, impacto e perfuração. Requer 3º círculo e afinidade.",
  },
  {
    id: "ouvir-os-sussurros",
    name: "Ouvir os Sussurros",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "completa",
    range: "pessoal",
    target: "você",
    duration: "instantânea",
    description:
      'O ritual conecta você com os sussurros, memórias ecoadas pelo Outro Lado, que você pode consultar para receber conhecimento proibido em relação a uma ação que tomará em breve. Ao usar este ritual, faça uma pergunta sobre um evento que você está prestes a fazer (na mesma cena) que possa ser respondida com "sim" ou "não". O mestre rola 1d6 em segredo; com um resultado de 2 a 6, o ritual funciona e você recebe sua resposta, que pode ser "sim", "não" ou "sim e não"\n\nCom um resultado 1, o ritual falha e oferece o resultado "não". Não há como saber se esse resultado foi dado porque o ritual falhou ou não. Lançar este ritual múltiplas vezes sobre o mesmo assunto gera sempre o primeiro resultado.\n\nPor exemplo, você está prestes a entrar em um prédio que pode ser o esconderijo de um cultista. Se você perguntar para os sussurros se o cultista está mesmo nesse local, a resposta pode ser "sim" (ele está no prédio), "não" (ele não está no prédio) ou "sim e não" (ele está no prédio, mas usou um ritual para se esconder seu corpo físico em uma dimensão do Outro Lado...). Isso é útil para saber se você deve (ou não) gastar recursos para um possível combate.\n\nDiscente (+2 PE): muda a execução para 1 minuto. Em vez do normal, você pode consultar os ecos fazendo uma pergunta sobre um evento que poderá acontecer até um dia no futuro. O mestre rola a chance de falha; com um resultado de 2 a 6, você recebe uma resposta, desde uma simples frase até uma profecia ou enigma. Em geral, este uso oferece pistas, indicando um caminho a tomar para descobrir a resposta que se procura. Numa falha você não recebe resposta alguma. Requer 2º círculo.\n\nVerdadeiro (+5 PE): muda a execução para 10 minutos e a duração para 5 rodadas. Em vez do normal, você consulta os ecos, podendo fazer uma pergunta por rodada, desde que ela possa ser respondida com "sim", "não" ou "ninguém sabe". O mestre rola a chance de falha para cada pergunta. Em caso de falha, a resposta também é "ninguém sabe". Requer 3º círculo.',
  },
  {
    id: "perturbacao",
    name: "Perturbação",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "curto",
    target: "1 pessoa",
    duration: "1 rodada",
    resistance: "Vontade (anula)",
    description:
      'Você dá uma ordem que o alvo deve ser capaz de ouvir (mas não precisa entender). Se falhar na resistência, ele deve obedecer à ordem em seu próprio turno da melhor maneira possível. Escolha um dos efeitos.\n\nFuja: O alvo gasta seu turno tentando se afastar de você (usando todas as suas ações).\n\nLargue: O alvo solta quaisquer itens que esteja segurando e não pode pegá-los novamente até o início de seu próximo turno. Como esta é uma ação livre, ele ainda pode executar outras ações (exceto pegar aquilo que largou).\n\nPare: O alvo fica pasmo (não pode realizar ações, só reações).\n\nSente-se: Com uma ação livre, o alvo se senta no chão (se estava pendurado ou voando, desce até o chão). Ele pode fazer outras ações, mas não se levantar até o início de seu próximo turno.\n\nVenha: O alvo gasta seu turno se aproximando de você (usando todas as suas ações).\n\nDiscente (+2 PE): muda o alvo para "1 ser" e adiciona o seguinte comando: "Sofra. O alvo é acometido de dor aguda, sofrendo 3d8 de dano de Conhecimento e ficando abalado por uma rodada".\n\nVerdadeiro (+5 PE): muda o alvo para "até 5 seres" ou adiciona o seguinte comando: "Ataque. O alvo deve fazer a ação agredir contra um outro alvo a sua escolha em alcance médio, com todas as suas capacidades". Requer 3º círculo e afinidade.',
    damage: "3d8",
    damageType: "Conhecimento",
  },
  {
    id: "polarizacao-caotica",
    name: "Polarização Caótica",
    level: 1,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "curto",
    target: "você",
    duration: "sustentada",
    resistance: "Vontade anula",
    description:
      'Você gera uma aura magnética sobrenatural. Escolha um dos efeitos a seguir.\n\nAtrair: você pode usar uma ação de movimento para puxar um objeto metálico de espaço 2 ou menor dentro do alcance. Se o objeto estiver livre, voa para suas mãos (caso tenha mãos livres para apanhá-lo) ou para seus pés.\n\nRepelir: você repele objetos de espaço 2 ou menor (o que envolve quase todos os projéteis e armas de arremesso), recebendo resistência a balístico, corte, impacto e perfuração 5.\n\nDiscente (+2 PE): nesta versão a energia magnética é expelida de uma única vez e arremessa até 10 objetos, ou um total de 10 espaços, o que for menor. Os objetos devem estar a até 3m uns dos outros. Objetos arremessados podem atingir seres em seu caminho, causando de 1 ponto de dano de impacto por espaço (objetos macios, sem pontas ou sem fio) até 1d6 pontos de dano por espaço (objetos duros, pontudos ou afiados). Seres atingidos têm direito a um teste de Reflexos para reduzir o dano à metade. Seres dentro da capacidade de carga do efeito podem ser arremessadas, mas têm direito a um teste de Vontade para evitar o efeito (em si mesmos ou em objetos que estejam segurando). Um ser arremessado contra uma superfície sólida sofre 1d6 pontos de dano de impacto para cada 3m que "voou" no deslocamento (incluindo outros seres; nesse caso, ambos sofrem o dano).\n\nVerdadeiro (+5 PE): muda o alcance para médio. Você pode usar uma ação de movimento para fazer com que a força magnética levite e mova um ser ou objeto de espaço 10 ou menor por até 9m em qualquer direção dentro do alcance. Um ser pode anular o efeito sobre ele, ou sobre um objeto que possua, passando num teste de Vontade. O alvo cai no chão se sair do alcance ou o efeito terminar.',
  },
  {
    id: "tecer-ilusao",
    name: "Tecer Ilusão",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "médio",
    target: "ilusão que se estende a até 4 cubos de 1,5m",
    duration: "cena",
    resistance: "Vontade desacredita",
    description:
      "Este ritual cria uma ilusão visual (uma pessoa, uma parede...) ou sonora (um grito de socorro, um uivo assustador...). O ritual cria apenas imagens ou sons simples, com volume equivalente à voz de uma pessoa para cada cubo de 1,5m no efeito. Não é possível criar cheiros, texturas ou temperaturas, nem sons complexos, como uma música ou diálogo. Seres e objetos atravessam uma ilusão sem sofrer dano, mas o ritual pode, por exemplo, esconder uma armadilha ou emboscada. A ilusão é dissipada se você sair do alcance.\n\nDiscente (+2 PE): muda o efeito para até 8 cubos de 1,5m e a duração para sustentada. Você pode criar ilusões de imagem e sons combinados, e pode criar sons complexos, odores e sensações térmicas. Também pode criar sensações táteis, como texturas; objetos ainda atravessam a ilusão, mas seres não conseguem atravessá-la sem passar em um teste de Vontade. A cada rodada, você pode usar uma ação livre para mover a imagem ou alterar o som, como aumentar o volume ou fazer com que pareça se afastar ou se aproximar, ainda dentro dos limites do efeito. Você pode, por exemplo, criar a ilusão de um fantasma que anda pela sala, controlando seus movimentos. A ilusão ainda é incapaz de causar ou sofrer dano. Quando você para de sustentar o ritual, a imagem ou som persistem por mais uma rodada antes do ritual se dissipar. Requer 2º círculo.\n\nVerdadeiro (+ 5 PE): você cria a ilusão de um perigo mortal. Quando o ritual é conjurado, e no início de cada um de seus turnos, um alvo interagindo com a ilusão deve fazer um teste de Vontade; se falhar, acredita que a ilusão é real e sofre 6d6 pontos de dano de Conhecimento. O alvo racionaliza o efeito sempre que falha no teste (por exemplo, acredita que o mesmo teto pode cair sobre ele várias vezes). Se um alvo passar em dois testes de Vontade seguidos, o efeito é anulado para ele. Requer 3º círculo.",
    damage: "6d6",
    damageType: "Conhecimento",
  },
  {
    id: "terceiro-olho",
    name: "Terceiro Olho",
    level: 1,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description:
      "Seus olhos se enchem de sigilos e você passa a enxergar auras paranormais em alcance longo. Rituais, itens amaldiçoados e criaturas emitem auras. Você sabe o elemento da aura e seu poder aproximado — rituais de 1º círculo e criaturas de VD até 80 emitem uma aura fraca; rituais de 2º e 3º círculos e criaturas de VD entre 81 e 280 emitem uma aura moderada, e rituais de 4º círculo e criaturas de VD 281 ou maior emitem uma aura poderosa.\n\nAlém disso, você pode gastar uma ação de movimento para descobrir se um ser que possa ver em alcance médio tem poderes paranormais ou se é capaz de conjurar rituais e de quais elementos.\n\nDiscente (+2 PE): muda a duração para 1 dia.\n\nVerdadeiro (+5 PE): também pode enxergar objetos e seres invisíveis, que aparecem como formas translúcidas.",
  },
  {
    id: "aprimorar-fisico",
    name: "Aprimorar Físico",
    level: 2,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description:
      "O alvo tem seus músculos tonificados e seus ligamentos reforçados, recebendo +1 em Agilidade ou Força, à escolha dele.\n\nDiscente (+3 PE): muda o bônus para +2. Requer 3º círculo.\n\nVerdadeiro (+7 PE): muda o bônus para +3. Requer 4º círculo e afinidade.",
  },
  {
    id: "aprimorar-mente",
    name: "Aprimorar Mente",
    level: 2,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description:
      "O alvo tem sua mente energizada por fagulhos do Conhecimento. Ele recebe +1 em Intelecto ou Presença, à escolha dele (esse aumento não fornece PE ou perícias treinadas).\n\nDiscente (+3 PE): muda o bônus para +2. Requer 3º círculo.\n\nVerdadeiro (+7 PE): muda o bônus para +3. Requer 4º círculo e afinidade.",
  },
  {
    id: "chamas-do-caos",
    name: "Chamas do Caos",
    level: 2,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "curto",
    target: "veja texto",
    duration: "cena",
    description:
      'Você manipula o calor e o fogo. Ao conjurar o ritual, escolha um dos seguintes efeitos.\n\nChamejar: o alvo é uma arma corpo a corpo. Ela causa +1d6 pontos de dano de fogo.\n\nEsquentar: o alvo é um objeto, que começa a esquentar. Ele sofre 1d6 pontos de dano de fogo por rodada e causa o mesmo dano a qualquer ser que o esteja empunhando ou vestindo. A critério do mestre, o objeto ou o ser pode pegar fogo. Um ser pode gastar uma ação completa para resfriar o objeto (jogando areia ou se jogando numa fonte de água próxima, por exemplo) e cancelar o efeito do ritual.\n\nExtinguir: o alvo é uma chama de tamanho Grande ou menor, que é apagada. Isso cria uma nuvem de fumaça que ocupa uma esfera de 3m de raio centrada onde estava a chama. Dentro da fumaça, seres têm camuflagem.\n\nModelar: o alvo é uma chama de tamanho Grande ou menor. A cada rodada, você pode gastar uma ação livre para movimentá-la 9m em qualquer direção. Se atravessar o espaço ocupado por um ser, ela causa 3d6 pontos de dano de fogo nele. Um ser só pode sofrer dano dessa maneira uma vez por rodada.\n\nDiscente (+3 PE): muda a duração para sustentada e adiciona "Resistência: Reflexos reduz à metade". Em vez do normal, uma vez por rodada você pode gastar uma ação de movimento para projetar uma labareda, num alvo em alcance curto. O alvo sofre 4d6 pontos de dano de Energia (Reflexos reduz à metade).\n\nVerdadeiro (+ 7 PE): como discente, mas muda o dano para 8d6. Requer 3º círculo.',
    damage: "3d6",
    damageType: "Fogo",
  },
  {
    id: "contencao-fantasmagorica",
    name: "Contenção Fantasmagórica",
    level: 2,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "médio",
    target: "1 ser",
    duration: "cena",
    resistance: "Reflexos anula",
    description:
      "Três laços de Energia surgem do chão e se enroscam no alvo, deixando-o agarrado. O alvo pode tentar se livrar, gastando uma ação padrão para fazer um teste de Atletismo (DT do ritual). Se passar, destrói um laço, mais um laço adicional para cada 5 pontos pelos quais superou a DT. Os laços também podem ser atacados e destruídos: cada um tem Defesa 10, 10 PV, RD 5 e imunidade a Energia. Se todos os laços forem destruídos, o ritual é dissipado. Por serem feitos de Energia, os laços afetam criaturas incorpóreas.\n\nDiscente (+3 PE): aumenta o número de laços para 6, e você pode escolher o alvo de cada laço, com um mínimo de dois laços por alvo. Requer 3º círculo.\n\nVerdadeiro (+5 PE): como discente, e cada laço destruído libera uma onda de choque que causa 2d6+2 pontos de dano de Energia no alvo agarrado. Requer 3º círculo e afinidade.",
    damage: "2d6+2",
    damageType: "Energia",
  },
  {
    id: "desacelerar-impacto",
    name: "Desacelerar Impacto",
    level: 2,
    type: "MORTE",
    castingTime: "reação",
    range: "curto",
    target: "1 ser ou objetos somando até 10 espaços",
    duration: "até chegar ao solo ou cena, o que vier primeiro",
    description:
      "O alvo cai lentamente. A velocidade da queda é reduzida para 18m por rodada — o suficiente para não causar dano. Como conjurar este ritual é uma reação, você pode conjurá-lo rápido o bastante para salvar a si ou um aliado de quedas inesperadas. Se o alvo for um projétil — como um disparo de arma ou um objeto largado do alto de um prédio —, o ritual faz com que ele cause metade do dano normal, devido à lentidão.Este ritual só funciona em alvos em queda livre ou similar; não pode frear um golpe de faca ou o mergulho rasante de um atacante voador.\n\nDiscente (+3 PE): aumenta o total de alvos para seres ou objetos somando até 100 espaços.",
  },
  {
    id: "descarnar",
    name: "Descarnar",
    level: 2,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Fortitude parcial",
    description:
      "Este ritual cruel faz com que lacerações se manifestem na pele e órgãos do alvo, que sofre 6d8 pontos de dano (metade corte, metade Sangue) e fica com uma hemorragia severa. No início de cada turno dele, o alvo deve fazer um teste de Fortitude. Se falhar, sofre 2d8 pontos de dano de Sangue. Se passar nesse teste dois turnos seguidos, a hemorragia é estancada. Alvos que passem no teste de resistência inicial sofrem metade do dano e não ficam com hemorragia.\n\nDiscente (+3 PE): muda o dano direto para 10d8 e o dano da hemorragia para 4d8. Requer 3º círculo.\n\nVerdadeiro (+7 PE): muda o alvo para você e a duração para sustentada. Enquanto o ritual durar, seus ataques corpo a corpo causam 4d8 pontos de dano de Sangue adicional e deixam o alvo com hemorragia automaticamente (como no efeito básico do ritual). O alvo ainda tem direito a um teste de Fortitude no início de seus turnos. Requer 3º círculo e afinidade.",
    damage: "6d8",
    damageType: "Sangue",
  },
  {
    id: "deteccao-de-ameacas",
    name: "Detecção de Ameaças",
    level: 2,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "pessoal",
    target: "esfera de 18m de raio",
    duration: "cena",
    description:
      'Você recebe uma percepção aguçada sobre perigos à sua volta. Quando um ser hostil ou armadilha entra na área do efeito, você tem uma sensação de perigo e pode gastar uma ação de movimento para fazer um teste de Percepção (DT 20). Se passar, sabe a direção e distância do perigo.\n\nDiscente (+3 PE): além do normal, você não fica desprevenido contra perigos detectados e recebe +5 em testes de resistência contra armadilhas. Requer 3º círculo.\n\nVerdadeiro (+5 PE): muda a duração para "1 dia" e concede os mesmos benefícios de discente. Requer 4º círculo.',
  },
  {
    id: "dissonancia-acustica",
    name: "Dissonância Acústica",
    level: 2,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "médio",
    target: "esfera com 6m de raio",
    duration: "sustentada",
    description:
      "Você manipula a vibração do ar, criando uma área de dissonância sonora. Enquanto estiverem na área, todos os seres ficam surdos. Essa dissonância também impede que seres dentro da área conjurem rituais.\n\nDiscente (+1 PE): muda a área para alvo de 1 objeto. Em vez do normal, o alvo emana uma área de silêncio com 3m de raio. Se conjurar o ritual num objeto de um ser involuntário, ele tem direito a um teste de Vontade para anulá-la.\n\nVerdadeiro (+3 PE): muda a duração para cena. Em vez do normal, nenhum som pode deixar a área, mas seres dentro da área podem falar, ouvir e conjurar rituais normalmente. Requer 3º círculo.",
  },
  {
    id: "eco-espiral",
    name: "Eco Espiral",
    level: 2,
    type: "MORTE",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "2 rodadas",
    resistance: "Fortitude reduz à metade",
    description:
      'Você manifesta em suas mãos uma pequena cópia do alvo feita de cinzas. No início do próximo turno após conjurar este ritual, você precisa gastar uma ação padrão para se concentrar nele; caso contrário, ele se dissipa sem efeito. No início do segundo turno, você precisa gastar uma ação padrão para descarregá-lo. Se fizer isso, a cópia explode e o alvo sofre dano de Morte igual a quantidade de dano que sofreu na rodada em que você se concentrou (Fortitude reduz à metade). Se não fizer, o ritual se dissipa sem efeito.\n\nDiscente (+3 PE): muda o alvo para "até 5 seres".\n\nVerdadeiro (+7 PE): muda a duração para "até 3 rodadas", permitindo que você se concentre nas duas primeiras e descarregue na terceira. Requer 4º círculo e afinidade.',
    damage: "Variável",
    damageType: "Morte",
  },
  {
    id: "esconder-dos-olhos",
    name: "Esconder dos Olhos",
    level: 2,
    type: "CONHECIMENTO",
    castingTime: "livre",
    range: "pessoal",
    target: "você",
    duration: "1 rodada",
    description:
      'Você fica invisível, incluindo seu equipamento, recebendo camuflagem total e +15 em testes de Furtividade. Como o normal, seres que não possam vê-lo ficam desprevenidos contra seus ataques.\n\nO efeito termina se você faz um ataque ou usa uma habilidade hostil. Ações contra objetos livres não dissipam Esconder dos Olhos (você pode tocar ou apanhar objetos que não estejam sendo segurados por outros seres). Causar dano indiretamente — por exemplo, preparar explosivos para detonar mais tarde — não é considerado um ataque.\n\nObjetos soltos voltam a ser visíveis e objetos apanhados por você ficam invisíveis. Uma luz transportada nunca fica invisível (mesmo que sua fonte seja). Qualquer parte de um item carregado que se estenda além de seu alcance corpo a corpo natural se torna visível.\n\nDiscente (+3 PE): muda a duração para "sustentada". Em vez do normal, você gera uma esfera de invisibilidade. Você e todos os aliados a até 3m de você se tornam invisíveis, como no efeito normal do ritual (ainda ficam visíveis caso façam uma ação hostil). A esfera se move juntamente com você; qualquer coisa que saia da esfera fica visível. Requer 3º círculo.\n\nVerdadeiro (+7 PE): muda a execução para "ação padrão", o alcance para "toque", o alvo para "1 ser" e a duração para "sustentada". O efeito não é dissipado caso o alvo faça um ataque ou ação hostil. Requer 4º círculo e afinidade.',
  },
  {
    id: "flagelo-de-sangue",
    name: "Flagelo de Sangue",
    level: 2,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 pessoa",
    duration: "cena",
    resistance: "Fortitude parcial",
    description:
      'Você toca uma pessoa, gravando uma marca escarificada no corpo dela enquanto profere uma ordem, como "não ataque a mim ou meus aliados", "siga-me" ou "não saia desta sala". A cada rodada que o alvo desobedecer a ordem, a marca inflige uma dor excruciante, que causa 10d6 pontos de dano de Sangue e deixa o alvo enjoado pela rodada (Fortitude reduz o dano à metade e evita a condição). Se o alvo passar nesse teste dois turnos seguidos a marca desaparece.\n\nDiscente (+3 PE): muda o alvo para "1 ser (exceto criaturas de Sangue)". Requer 3º círculo.\n\nVerdadeiro (+7 PE): como Discente, e muda a duração para "1 dia". Requer 4º círculo e afinidade.',
    damage: "10d6",
    damageType: "Sangue",
  },
  {
    id: "hemofagia",
    name: "Hemofagia",
    level: 2,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    resistance: "Fortitude reduz à metade",
    description:
      'Você arranca o sangue do corpo do alvo através de pele dele, causando 6d6 pontos de dano de Sangue. Você então absorve esse sangue, recuperando pontos de vida iguais à metade do dano causado.\n\nDiscente (+3 PE): muda a resistência para "nenhuma". Como parte da execução do ritual, você pode usar uma arma em vez das mãos para fazer um ataque corpo a corpo contra o alvo. Se acertar, causa o dano do ataque e do ritual, recuperando pontos de vida em quantidade igual à metade do dano total causado.\n\nVerdadeiro (+7 PE): muda o alcance para "pessoal", o alvo para "você" e a duração para "cena". Em vez do normal, a cada rodada você pode gastar uma ação padrão para tocar 1 ser e causar 4d6 pontos de dano de Sangue. Você recupera pontos de vida iguais à metade do dano causado. Requer 4º círculo.',
    damage: "6d6",
    damageType: "Sangue",
  },
  {
    id: "invadir-mente",
    name: "Invadir Mente",
    level: 2,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "médio ou toque",
    target: "1 ser ou 2 pessoas voluntárias",
    duration: "instantânea ou 1 dia",
    resistance: "Vontade parcial ou nenhuma",
    description:
      'Quando conjura este ritual, você gera um dos efeitos a seguir, a sua escolha: rajada mental (usa os primeiros parâmetros do cabeçalho acima) ou ligação telepática (usa os segundos parâmetros).\n\nRajada Mental: você infecta a mente do alvo com o Conhecimento proibido do Outro Lado, dilacerando o cérebro dele. O alvo sofre 6d6 pontos de dano de Conhecimento e fica atordoado por uma rodada. Se passar no teste de Vontade, sofre metade do dano e não fica atordoado. Um mesmo alvo só pode ficar atordoado por este ritual uma vez por cena.\n\nLigação Telepática: você cria um elo mental entre duas pessoas (você pode ser uma delas), que podem se comunicar independente da distância pela duração do ritual (1 dia).\n\nDiscente (+3 PE): se escolhar rajada mental, aumenta o dano para 10d6. Se escolher ligação telepática, em vez do normal, você cria um elo mental que permite que você veja e ouça pelos sentidos do alvo, gastando uma ação de movimento para se concentrar. Um alvo involuntário pode fazer um teste de Vontade para suprimir o ritual por uma hora. Requer 3º círculo.\n\nVerdadeiro (+ 7 PE): se escolher rajada mental, aumenta o dano para 10d6 e muda o alvo para todos os "seres escolhidos". Se escolher ligação telepática, você pode criar um vínculo mental entre até 5 pessoas. Requer 4º círculo.',
    damage: "6d6",
    damageType: "Conhecimento",
  },
  {
    id: "localizacao",
    name: "Localização",
    level: 2,
    type: "CONHECIMENTO",
    castingTime: "padrão",
    range: "pessoal",
    target: "círculo com 90m de raio",
    duration: "cena",
    description:
      'Esta ritual pode encontrar uma pessoa ou objeto a sua escolha. Você pode pensar em termos gerais ("um policial", "algo de metal") ou específicos ("A delegada Joana", "uma pistola"). O ritual indica a direção e distância da pessoa ou objeto mais próximo desse tipo, caso esteja ao alcance. Você pode movimentar-se para continuar procurando. Procurar algo muito específico ("a chave do armazém 4 no porto") exige que você tenha em mente uma imagem precisa do objeto; caso a imagem não seja parecida com a verdade, o ritual falha, mas você gasta os PE mesmo assim. Este ritual pode ser bloqueado por uma fina camada de chumbo.\n\nDiscente (+3 PE): muda o alcance para "toque", o alvo para "1 pessoa" e a duração para "1 hora". Em vez do normal, a pessoa tocada descobre o caminho mais direto para entrar ou sair de um lugar. Assim, o ritual pode ser usado para descobrir a rota até o relicário de uma catedral ou a saída mais próxima de uma caverna (mas não para encontrar a localização de uma pessoa ou objeto; funciona apenas em relação a lugares). Caso a pessoa demore mais de uma hora para percorrer o caminho, o conhecimento se perde.\n\nVerdadeiro (+7 PE): aumenta a área para círculo de 1km de raio. Requer 4º círculo.',
  },
  {
    id: "miasma-entropico",
    name: "Miasma Entrópico",
    level: 2,
    type: "MORTE",
    castingTime: "padrão",
    range: "médio",
    target: "nuvem com 6m de raio",
    duration: "instantânea",
    resistance: "Fortitude parcial",
    description:
      "Cria uma explosão de emanações tóxicas. Seres na área sofrem 4d8 pontos de dano químico e ficam enjoados por 1 rodada. Se passarem na resistência, sofrem metade do dano e não ficam enjoados.\n\nDiscente (+3 PE): muda o dano para 6d8 de Morte.\n\nVerdadeiro (+7 PE): muda a duração para 3 rodadas. Um ser que inicie seu turno dentro da área sofre o dano novamente. Requer 3º círculo.",
    damage: "4d8",
    damageType: "Químico",
  },
  {
    id: "paradoxo",
    name: "Paradoxo",
    level: 2,
    type: "MORTE",
    castingTime: "padrão",
    range: "médio",
    target: "esfera com 6m de raio",
    duration: "instantânea",
    resistance: "Fortitude reduz à metade",
    description:
      'O ritual cria uma poderosa implosão de distorção temporal contraditória, causando 6d6 pontos de dano de Morte em todos os seres na área.\n\nDiscente (+3 PE): muda a área para "efeito: esfera com tamanho Médio" e a duração para cena. Em vez do normal, cria uma esfera de emanações espirais sibilantes com 1,5m de diâmetro que causa 4d6 pontos de dano de Morte a qualquer ser no mesmo espaço. Você pode gastar uma ação de movimento para fazer a esfera voar 9m em qualquer direção. Um ser só pode sofrer dano da esfera uma vez por rodada.\n\nVerdadeiro (+7 PE): muda o dano para 13d6. Seres reduzidos a 0 PV pelo dano do Paradoxo devem fazer um teste de Fortitude. Se falharam, são reduzidas a cinzas (morrem imediatamente). Requer 4º círculo.',
    damage: "6d6",
    damageType: "Morte",
  },
  {
    id: "protecao-contra-rituais",
    name: "Proteção contra Rituais",
    level: 2,
    type: "MEDO",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "cena",
    description:
      'Você canaliza uma aura de Medo puro, que protege o alvo contra efeitos paranormais. O alvo recebe resistência a paranormal 5 e +5 em testes de resistência contra rituais e habilidades de criaturas paranormais.\n\nDiscente (+3 PE): muda o alvo para "até 5 seres tocados". Requer 3º círculo.\n\nVerdadeiro(+6 PE): muda o alvo para "até 5 seres tocados", a resistência a dano para 10 e o bônus em testes de resistência para +10. Requer 4º círculo.',
  },
  {
    id: "rejeitar-nevoa",
    name: "Rejeitar Névoa",
    level: 2,
    type: "MEDO",
    castingTime: "padrão",
    range: "curto",
    target: "nuvem de 6m de raio",
    duration: "cena",
    description:
      "Você manifesta um leve redemoinho de névoa que se movimenta suavemente dentro da área. Rituais conjurados dentro da área têm seu custo aumentado em +2 PE por círculo e sua execução aumentada em um passo (de livre para movimento, de movimento para padrão, de padrão para completa, de completa para duas rodadas). Rejeitar a Névoa anula os efeitos de Cinerária, a menos que o conjurador de Cinerária use uma ação completa por rodada para manter o ritual ativo, neutralizando o efeito dos dois rituais.\n\nDiscente (+2 PE): além do normal, a DT de testes de resistência contra rituais realizados na área diminui em –5.\n\nVerdadeiro (+ 5 PE): como discente, e o dano causado dentro da névoa por rituais é sempre mínimo.",
  },
  {
    id: "sopro-do-caos",
    name: "Sopro do Caos",
    level: 2,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "médio",
    target: "varia",
    duration: "sustentada",
    resistance: "veja texto",
    description:
      'Você altera os movimentos de massas de ar de forma caótica. Ao conjurar o ritual, escolha um dos efeitos abaixo.\n\nAscender: cria uma corrente de ar ascendente capaz de erguer do chão um ser ou objeto Médio, fazendo o alvo flutuar para cima e para baixo conforme sua vontade. Você pode gastar uma ação de movimento para subir ou descer o alvo até 6m por rodada, até um máximo de 30m de altura. Você não pode mover o alvo horizontalmente — mas o alvo pode, por exemplo, escalar uma colina ou se apoiar no teto para mover-se lateralmente (com metade de seu deslocamento normal). Um ser levitando fica vulnerável. Alvos involuntários têm direito a um teste de Fortitude no início de cada um de seus turnos para encerrar o efeito. Derrubar um alvo flutuando (simplesmente parando a corrente de ar) causa o dano normal de queda, mas um alvo que passe no teste pode "nadar" para o chão contra a corrente. Você pode usar essa opção para fazer uma manobra derrubar contra um alvo voador dentro do alcance, usando Ocultismo em vez de Luta.\n\nSopro: cria uma lufada de vento a partir de suas mãos, que empurra qualquer alvo Médio ou menor, em um cone de 4,5m — faça uma manobra empurrar usando Ocultismo em vez de Luta, usando uma mesma rolagem sua para todos os alvos. A lufada de vento também faz qualquer coisa que um vento forte e súbito faria, como levantar pó, dispersar vapores, apagar chamas, espalhar papéis ou mover uma embarcação. Manter o sopro ativo exige uma ação padrão no seu turno.\n\nVento: cria uma área de vento forte dentro do alcance. Se conjurada numa área que já esteja com algum efeito de vento, aumenta esse efeito em um passo. Manter o vento ativo requer uma ação de movimento. Você também pode usar essa opção para reduzir os efeitos de vento em uma área.\n\nDiscente (+3 PE): passa a afetar alvos Grandes.\n\nVerdadeiro (+9 PE): passa a afetar alvos Enormes.',
  },
  {
    id: "tela-de-ruido",
    name: "Tela de Ruído",
    level: 2,
    type: "ENERGIA",
    castingTime: "padrão",
    range: "pessoal",
    target: "você",
    duration: "cena",
    description:
      "Este ritual cria uma película de energia que recobre seu corpo e absorve energia cinética. Você recebe 30 PV temporários, mas apenas contra dano balístico, de corte, de impacto ou de perfuração.\n\nAlternativamente, você pode conjurar este ritual como uma reação quando sofrer dano, recebendo resistência 15 apenas contra esse dano.\n\nDiscente (+3 PE): aumenta os PV temporário para 60 e a resistência para 30.\n\nVerdadeiro (+7 PE): muda o alcance para curto e o alvo para 1 ser ou objeto Enorme ou menor. Em vez do normal, cria uma esfera imóvel e tremeluzente com o tamanho do alvo e centrada nele. Nenhum ser, objeto ou efeito de dano pode passar pela esfera, embora seres possam respirar normalmente dentro dela. O alvo tem direito a um teste de Reflexo para evitar ser aprisionado. Requer 4º círculo.",
  },
  {
    id: "transfusao-vital",
    name: "Transfusão Vital",
    level: 2,
    type: "SANGUE",
    castingTime: "padrão",
    range: "toque",
    target: "1 ser",
    duration: "instantânea",
    description:
      "Você toca no alvo e transfere sua própria energia vital para ele, podendo sofrer até 30 pontos de dano de Sangue para que o alvo recupere a mesma quantidade em PV. Você não pode ficar com menos de 1 PV por causa desse ritual.\n\nDiscente (+3 PE): Você pode transferir até 50 pontos de vida. Requer 3º círculo.\n\nVerdadeiro (+7 PE): Você pode transferir até 100 pontos de vida. Requer 4º círculo.",
  },
  {
    id: "velocidade-mortal",
    name: "Velocidade Mortal",
    level: 2,
    type: "MORTE",
    castingTime: "padrão",
    range: "curto",
    target: "1 ser",
    duration: "sustentada",
    description:
      'Você distorce a passagem do tempo ao redor do alvo, tornando-o extremamente veloz. O alvo pode realizar uma ação de movimento adicional por turno. Esta ação não pode ser usada para conjurar rituais.\n\nDiscente (+3 PE): em vez de uma ação de movimento, o alvo recebe uma ação padrão adicional por turno.\n\nVerdadeiro (+7 PE): muda o alvo para "alvos escolhidos". Requer 4º círculo e afinidade.',
  },
]
