export interface WeaponData {
  name: string
  category: string
  damage: string
  critical: string
  range: string
  type: string
  space: number
  description?: string
}

export const meleeWeapons: WeaponData[] = [
  {
    name: "Acha",
    category: "I",
    damage: "1d12",
    critical: "20 - x2",
    range: "Curto",
    type: "C - Impacto",
    space: 2,
  },
  {
    name: "Gadanho",
    category: "I",
    damage: "4d4",
    critical: "20 - x3",
    range: "Curto",
    type: "C - Corte",
    space: 1,
  },
  {
    name: "Katana",
    category: "I",
    damage: "1d10",
    critical: "19 - x2",
    range: "Curto",
    type: "C - Perfuração",
    space: 1,
  },
  {
    name: "Montante",
    category: "I",
    damage: "2d6",
    critical: "19 - x2",
    range: "Curto",
    type: "C - Perfuração",
    space: 2,
  },
  {
    name: "Motosserra",
    category: "II",
    damage: "3d6",
    critical: "18 - x2",
    range: "Curto",
    type: "C - Corte",
    space: 2,
  },
  {
    name: "Faca",
    category: "I",
    damage: "1d4+FOR",
    critical: "20 - x3",
    range: "Curto",
    type: "C - Perfuração",
    space: 1,
  },
  {
    name: "Soqueira",
    category: "I",
    damage: "1d6+FOR",
    critical: "18 - x2",
    range: "Curto",
    type: "C - Impacto",
    space: 1,
  },
  {
    name: "Nunchaku",
    category: "I",
    damage: "2d6+FOR",
    critical: "17 - x4",
    range: "Curto",
    type: "C - Impacto",
    space: 1,
  },
  {
    name: "Foice",
    category: "II",
    damage: "1d10",
    critical: "20 - x3",
    range: "Curto",
    type: "C - Corte",
    space: 2,
  },
]

export const rangedWeapons: WeaponData[] = [
  {
    name: "Espingarda",
    category: "I",
    damage: "4d6",
    critical: "20 - x3",
    range: "Curto",
    type: "Balístico",
    space: 1,
  },
  {
    name: "Fuzil De Assalto",
    category: "II",
    damage: "2d10",
    critical: "19 - x2",
    range: "Médio",
    type: "Balístico",
    space: 2,
  },
  {
    name: "Fuzil De Precisão",
    category: "III",
    damage: "4d6",
    critical: "18 - x2",
    range: "Longo",
    type: "Balístico",
    space: 2,
  },
  {
    name: "Pistola",
    category: "I",
    damage: "1d12",
    critical: "18 - x2",
    range: "Curto",
    type: "Balístico",
    space: 1,
  },
  {
    name: "Revólver",
    category: "II",
    damage: "3d6",
    critical: "18 - x3",
    range: "Médio",
    type: "Balístico",
    space: 1,
  },
  {
    name: "Submetralhadora",
    category: "I",
    damage: "2d6",
    critical: "20 - x2",
    range: "Médio",
    type: "Balístico",
    space: 2,
  },
  {
    name: "Fuzil De Caça",
    category: "II",
    damage: "2d8",
    critical: "19 - x3",
    range: "Médio",
    type: "Balístico",
    space: 2,
  },
]

export const cursedWeapons: WeaponData[] = [
  {
    name: "Machado Do Flagelo",
    category: "II",
    damage: "2d10+5",
    critical: "20 - x2",
    range: "Curto",
    type: "C - Corte",
    space: 2,
    description: "Um machado amaldiçoado que causa dano adicional",
  },
  {
    name: "Dentadura Monstruosa",
    category: "I",
    damage: "1d8+5",
    critical: "20 - x3",
    range: "Curto",
    type: "C - Perfuração",
    space: 0,
    description: "Uma dentadura que morde seus inimigos",
  },
  {
    name: "Garras Do Diabo",
    category: "III",
    damage: "4d6+10",
    critical: "17 - x4",
    range: "Curto",
    type: "C - Corte",
    space: 1,
    description: "Garras demoníacas que rasgam a carne",
  },
  {
    name: "Faca Do Hiu",
    category: "III",
    damage: "4d6+5",
    critical: "18 - x2",
    range: "Curto",
    type: "C - Perfuração",
    space: 1,
    description: "Uma faca amaldiçoada que nunca perde o fio",
  },
  {
    name: "Lâminas Do Caçador",
    category: "III",
    damage: "7d6+3",
    critical: "17 - x3",
    range: "Médio",
    type: "C - Perfuração",
    space: 2,
    description: "Lâminas que sempre encontram seu alvo",
  },
  {
    name: "Espingarda Caótica",
    category: "III",
    damage: "4d?+10",
    critical: "? - x?",
    range: "Curto",
    type: "B - Balístico",
    space: 2,
    description: "Uma espingarda imprevisível que causa danos aleatórios",
  },
]

export const protectionItems = [
  {
    name: "Proteção Leve",
    defense: 5,
    category: "I",
    space: 3,
    description: "Proteção básica que oferece mobilidade",
  },
  {
    name: "Proteção Pesada",
    defense: 10,
    category: "II",
    space: 5,
    description: "Proteção robusta para combates intensos",
  },
  {
    name: "Proteção Militar",
    defense: 15,
    category: "III",
    space: 7,
    description: "Proteção de alta qualidade usada por forças militares",
  },
  {
    name: "Proteção Elite",
    defense: 20,
    category: "IV",
    space: 10,
    description: "A melhor proteção disponível, usada por forças especiais",
  },
]
